### ISSUE TITLE
is this supposed to work at start ?

### ISSUE THREAD

**Issue by axe-z** [jscomplete/learn-fullstack-javascript#2]
/Users/axez/Desktop/Learning Full-Stack javascript Development_ MongoDB, Node and React/learn-fullstack-javascript-master/node_modules/mongodb/lib/mongo_client.js:377
          throw err
          ^
AssertionError: null == { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

**Comment by iMateo** [comment]
It telling you that something wrong with your MondoDB. Check DB server and try again.

**Comment by axe-z** [comment]
it's the starting files... the ones you've done

**Comment by axe-z** [comment]
So , it's kind of hard to go trough a course with bugs in the setup.

**Comment by lucask42** [comment]
In order to get this project working on your computer you would have had to set up your local environment and also set up and run MongoDB.

You don't need any of these files to go through the course - I recommend following along the course and creating all the files as you go.  It might help in certain cases to copy/paste from files in this repo.

Good luck!

**Comment by danilocecilia** [comment]
it´s been really messy trying to follow the steps from the course, lot´s of differences in code and many bugs due to deprecated ...

**Comment by samerbuna** [comment]
All the files and tags of this repo were updated for things to work with the latest changes in the tools.
